# Makefile for the C Task Manager

# 1. Variables
# The compiler we'll use
CC = gcc

# Compiler flags:
# -Wall: Show all warnings
# -g: Include debugging information in the executable
CFLAGS = -Wall -g

# The directory for our source code files
SRC_DIR = src

# The directory where compiled objects and the final executable will be placed
BUILD_DIR = build

# The name of our final executable program
TARGET = $(BUILD_DIR)/task_manager

# Find all .c files in the src directory and create a list of corresponding .o files
# in the build directory. e.g., src/main.c becomes build/main.o
SRCS = $(wildcard $(SRC_DIR)/*.c)
OBJS = $(patsubst $(SRC_DIR)/%.c, $(BUILD_DIR)/%.o, $(SRCS))


# 2. Rules

# The first rule is the default one, executed when you just type "make"
# Its target is our final program, which depends on all object files.
all: $(TARGET)

# Rule to create the final executable program
# It depends on all object (.o) files.
$(TARGET): $(OBJS)
	@mkdir -p $(BUILD_DIR) # Create the build directory if it doesn't exist
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS)
	@echo "Project compiled successfully! Executable at: $(TARGET)"

# Generic rule to create any .o file from a corresponding .c file
# e.g., to create build/main.o, it will use src/main.c
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(BUILD_DIR) # Create the build directory if it doesn't exist
	$(CC) $(CFLAGS) -c $< -o $@

# "clean" rule: removes all files generated by the compilation.
# Useful for forcing a full, fresh rebuild from scratch.
clean:
	@echo "Cleaning up build files..."
	rm -rf $(BUILD_DIR)

# .PHONY tells make that "all" and "clean" are not real file names.
# This prevents issues if you ever create a file named "clean".
.PHONY: all clean